### ISSUE TITLE
Updated information/data

### ISSUE THREAD

**Issue by jedevc** [CSSUoB/sponsor#1]
I'm guessing we have some new PDFs for this year? It would be great to get them on the site here so we can promote this a bit more.

Also, slightly unrelated, it would be great if we could keep the source files for whatever the PDF was generated with here as well, in a subdirectory.

**Comment by jontyrudman** [comment]
I've updated the repo with what is pretty much an exact copy of the original doc, with the new year and logo, and in Noto (partially because I couldn't find the font.

I've uploaded the source too. It'd still be good to have a look over the doc to see if anything needs changing.

**Comment by jedevc** [comment]
This look pretty good, thanks!
